/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'areese' at '6/28/16 3:24 PM' with Gradle 2.12
 *
 * @author areese, @date 6/28/16 3:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
